version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - "55038:8000"
      - "5173:5173"
    working_dir: /var/www
    command: /bin/bash -c "npm install && npm run dev & php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - python
      - mysql
    networks:
      - laravel_net

  python:
    image: python:3.10
    container_name: python_service
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - laravel_net
    command: /bin/bash -c "cd /app/app/python/bangdosao && pip install --break-system-packages -r requirements.txt && tail -f /dev/null"

  mysql:
    image: mysql:8.0
    container_name: mysql_service
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: he_thong_chiem_tinh
      MYSQL_USER: he_thong_chiem_tinh
      MYSQL_PASSWORD: 6ymsPLGMwJzwRcp
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge

volumes:
  mysql_data:
