version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - "8888:8000"
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - python
    networks:
      - laravel_net

  # web:
  #   image: nginx:alpine
  #   container_name: laravel_web
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - .:/var/www
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - app
  #   networks:
  #     - laravel_net

  python:
    image: python:3.10
    container_name: python_service
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - laravel_net
    command: tail -f /dev/null # để container luôn chạy

networks:
  laravel_net:
    driver: bridge